import astropy.constants as constants

length_dictionary = {
    "qm": 1e-30,
    "rm": 1e-27,
    "ym": 1e-24,
    "zm": 1e-21,
    "am": 1e-18,
    "fm": 1e-15,
    "pm": 1e-12,
    "nm": 1e-9,
    "um": 1e-6,
    "mm": 1e-3,
    "cm": 1e-2,
    "dm": 1e-1,
    "m": 1,
    "dam": 1e1,
    "hm": 1e2,
    "km": 1e3,
    "Mm": 1e6,
    "Gm": 1e9,
    "Tm": 1e12,
    "Pm": 1e15,
    "Em": 1e18,
    "Zm": 1e21,
    "Ym": 1e24,
    "Rm": 1e27,
    "Qm": 1e30,
    "a0": constants.a0.value,  # Bohr radius
    "R_earth": constants.R_earth.value,
    "R_jup": constants.R_jup.value,
    "R_sun": constants.R_sun.value,
    "au": constants.au.value,
    "kpc": constants.kpc.value,
    "pc": constants.pc.value,
}
mass_dictionary = {
    "qg": 1e-30,
    "rg": 1e-27,
    "yg": 1e-24,
    "zg": 1e-21,
    "ag": 1e-18,
    "fg": 1e-15,
    "pg": 1e-12,
    "ng": 1e-9,
    "ug": 1e-6,
    "mg": 1e-3,
    "cg": 1e-2,
    "dg": 1e-1,
    "g": 1,
    "dag": 1e1,
    "hg": 1e2,
    "kg": 1e3,
    "Mg": 1e6,
    "Gg": 1e9,
    "Tg": 1e12,
    "Pg": 1e15,
    "Eg": 1e18,
    "Zg": 1e21,
    "Yg": 1e24,
    "Rg": 1e27,
    "m_e": constants.m_e.value * 1e3,
    "m_n": constants.m_n.value * 1e3,
    "m_p": constants.m_p.value * 1e3,
    "u": constants.u.value * 1e3,
    "M_earth": constants.M_earth.value * 1e3,
    "M_jup": constants.M_jup.value * 1e3,
    "M_sun": constants.M_sun.value * 1e3,
}


def unit_dict():
    return [length_dictionary, mass_dictionary]
